// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var VideoGame$ReactTemplate = require("./VideoGame.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("VideoGameList");

function make(items, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("ul", {
                          style: {
                            listStyleType: "none"
                          }
                        }, $$Array.map((function (item) {
                                return React.createElement("li", {
                                            key: item[/* id */0]
                                          }, React.createElement("input", {
                                                id: item[/* id */0],
                                                checked: item[/* completed */3],
                                                type: "checkbox"
                                              }), React.createElement("label", {
                                                htmlFor: item[/* id */0]
                                              }, item[/* title */1] + (" | " + item[/* developer */2])));
                              }), $$Array.map(VideoGame$ReactTemplate.videoGameFromJs, items)));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.str = str;
exports.component = component;
exports.make = make;
/* component Not a pure module */
